# Generated by gallery/generate.py; do not edit.
function railcraft_gallery:clear
# void-chest-north-dry: north-facing dry void chest
setblock 164 100 164 railcraft:void_chest[facing=north,waterlogged=false]
# void-chest-east-dry: east-facing dry void chest
setblock 168 100 164 railcraft:void_chest[facing=east,waterlogged=false]
# void-chest-south-dry: south-facing dry void chest
setblock 172 100 164 railcraft:void_chest[facing=south,waterlogged=false]
# void-chest-west-dry: west-facing dry void chest
setblock 176 100 164 railcraft:void_chest[facing=west,waterlogged=false]
# void-chest-north-waterlogged: north-facing waterlogged void chest
setblock 164 100 168 railcraft:void_chest[facing=north,waterlogged=true]
# void-chest-east-waterlogged: east-facing waterlogged void chest
setblock 168 100 168 railcraft:void_chest[facing=east,waterlogged=true]
# void-chest-south-waterlogged: south-facing waterlogged void chest
setblock 172 100 168 railcraft:void_chest[facing=south,waterlogged=true]
# void-chest-west-waterlogged: west-facing waterlogged void chest
setblock 176 100 168 railcraft:void_chest[facing=west,waterlogged=true]
# vanilla-single-chest-control: north-facing vanilla single-chest control
setblock 180 100 164 minecraft:chest[facing=north,type=single,waterlogged=false]
function railcraft_gallery:verify
