# Generated by gallery/generate.py; do not edit.
execute unless block 164 100 164 railcraft:void_chest[facing=north,waterlogged=false] run tellraw @a {"text":"gallery mismatch: void-chest-north-dry","color":"red"}
execute unless block 168 100 164 railcraft:void_chest[facing=east,waterlogged=false] run tellraw @a {"text":"gallery mismatch: void-chest-east-dry","color":"red"}
execute unless block 172 100 164 railcraft:void_chest[facing=south,waterlogged=false] run tellraw @a {"text":"gallery mismatch: void-chest-south-dry","color":"red"}
execute unless block 176 100 164 railcraft:void_chest[facing=west,waterlogged=false] run tellraw @a {"text":"gallery mismatch: void-chest-west-dry","color":"red"}
execute unless block 164 100 168 railcraft:void_chest[facing=north,waterlogged=true] run tellraw @a {"text":"gallery mismatch: void-chest-north-waterlogged","color":"red"}
execute unless block 168 100 168 railcraft:void_chest[facing=east,waterlogged=true] run tellraw @a {"text":"gallery mismatch: void-chest-east-waterlogged","color":"red"}
execute unless block 172 100 168 railcraft:void_chest[facing=south,waterlogged=true] run tellraw @a {"text":"gallery mismatch: void-chest-south-waterlogged","color":"red"}
execute unless block 176 100 168 railcraft:void_chest[facing=west,waterlogged=true] run tellraw @a {"text":"gallery mismatch: void-chest-west-waterlogged","color":"red"}
execute unless block 180 100 164 minecraft:chest[facing=north,type=single,waterlogged=false] run tellraw @a {"text":"gallery mismatch: vanilla-single-chest-control","color":"red"}
tellraw @a {"text":"Railcraft void-chest gallery checked: 9 blocks","color":"green"}
